
----------------------------------
-- Tablespace create 
----------------------------------
CREATE TABLESPACE LAUREN
  DATAFILE 'LAUREN.dat' 
    SIZE 10M
  AUTOEXTEND ON;
  
----------------------------------
-- Schema create
----------------------------------
CREATE USER CMS
  IDENTIFIED BY cmsadmin
  DEFAULT TABLESPACE LAUREN
  QUOTA 10M on LAUREN;
  
GRANT create session TO cms;
GRANT create table TO cms;
GRANT create view TO cms;
GRANT create any trigger TO cms;
GRANT create any procedure TO cms;
GRANT create sequence TO cms;
GRANT create synonym TO cms;

----------------------------------
-- DDL for Table CUSTOMERS 
----------------------------------
CREATE TABLE "CMS"."CUSTOMERS"
	(	"CSTMR_ID" NUMERIC(10),
		"CSTMR_LAST_NM" VARCHAR(100),
		"CSTMR_FIRST_NM" VARCHAR(50),
		"CSTMR_MID_INIT" CHAR(1),
		"ENTRY_DT" DATE,
		"LAST_UPD_DT" DATE,
		"CSTMR_TITLE" VARCHAR(10)
	) TABLESPACE "LAUREN"
	/

---------------------------------
-- DDL for Table CUSTOMER_ADDRESS
---------------------------------
CREATE TABLE "CMS"."CUSTOMER_ADDRESS"
	(	"ADDR_ID" NUMERIC(10),
		"STREET_LINE_1" VARCHAR(100),
		"STREET_LINE_2" VARCHAR(100),
		"CITY_NM" VARCHAR(100),
		"STATE_CD" VARCHAR(2),
		"CNTRY_CD" VARCHAR(2),
		"ZIP_CD" VARCHAR(9),
		"DEFAULT_IND" CHAR(1),
		"CSTMR_ID" NUMERIC(10)
	) TABLESPACE "LAUREN"
	/

---------------------------------
-- DDL for Table CUSTOMER_CONTACT
---------------------------------
CREATE TABLE "CMS"."CUSTOMER_CONTACT"
	(	"CNTCT_ID" NUMERIC(10),
		"HOME_PHONE_NBR" NUMERIC(15),
		"MOBILE_PHONE_NBR" NUMERIC(15),
		"EMAIL_ADDR" VARCHAR(100),
		"DEFAULT_IND" CHAR(1),
		"PREFERRED_METHOD_CD" CHAR(1),
		"CSTMR_ID" NUMERIC(10)
	) TABLESPACE "LAUREN"
	/

---------------------------------
-- DDL for Table ORDERS
---------------------------------
CREATE TABLE "CMS"."ORDERS"
	(	"ORDR_ID" NUMERIC(10),
		"ORDR_DT" DATE,
		"ORDR_TOTAL_COST" DECIMAL(10,2),
		"SHIPPING_METHOD_CD" CHAR(1),
		"DELIVERY_DT" DATE,
		"CANCEL_IND" CHAR(1),
		"COMPLETE_IND" CHAR(1),
		"RETURN_IND" CHAR(1),
		"ORDR_STAT_CD" CHAR(1),
		"CNTCT_ID" NUMERIC(10),
		"CSTMR_ID" NUMERIC(10),
		"ADDR_ID" NUMERIC(10)
	) TABLESPACE "LAUREN"
	/

---------------------------------
-- DDL for Table ORDER_STATUS
---------------------------------
CREATE TABLE "CMS"."ORDER_STATUS"
	(	"ORDR_STAT_CD" CHAR(1),
		"DESCRIPTION" VARCHAR(100)
	) TABLESPACE "LAUREN"
	/

---------------------------------
-- DDL for Table ORDER_TRACKING
---------------------------------
CREATE TABLE "CMS"."ORDER_TRACKING"
	(	"ORDR_HIST_ID" NUMERIC(10),
		"STAT_DT" DATE,
		"ORDR_ID" NUMERIC(10),
		"ORDR_STAT_CD" CHAR(1),
		"NOTES" VARCHAR(250)
	) TABLESPACE "LAUREN"
	/

---------------------------------
-- DDL for Table ORDER_CONTENTS
---------------------------------
CREATE TABLE "CMS"."ORDER_CONTENTS"
	(	"ORDR_CONTENTS_ID" NUMERIC(10),
		"ORDR_ID" NUMERIC(10),
		"PRDCT_ID" NUMERIC(10),
		"PRDCT_CNT" NUMERIC(10)
	) TABLESPACE "LAUREN"
	/

---------------------------------
-- DDL for Table PRODUCTS
---------------------------------
CREATE TABLE "CMS"."PRODUCTS"
	(	"PRDCT_ID" NUMERIC(10),
		"DESCRIPTION" VARCHAR(250),
		"IN_STOCK_IND" CHAR(1),
		"PRICE_PER_UNIT" DECIMAL(10,2)
	) TABLESPACE "LAUREN"
	/

---------------------------------
-- DDL for Table STATE
---------------------------------
CREATE TABLE "CMS"."STATE"
	(	"STATE_CD" VARCHAR(2),
		"DESCRIPTION" VARCHAR(100),
		"CNTRY_CD" VARCHAR(2)
	) TABLESPACE "LAUREN"
	/
	
---------------------------------
-- DDL for Table COUNTRY
---------------------------------
CREATE TABLE "CMS"."COUNTRY"
	(	"CNTRY_CD" VARCHAR(2),
		"DESCRIPTION" VARCHAR(100)
	) TABLESPACE "LAUREN"
	/

----------------------------------
-- Constraints for Table CUSTOMERS
----------------------------------
ALTER TABLE "CMS"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("CSTMR_ID")
USING INDEX
TABLESPACE "LAUREN" ENABLE;

ALTER TABLE "CMS"."CUSTOMERS" MODIFY ("CSTMR_ID" NOT NULL ENABLE);

ALTER TABLE "CMS"."CUSTOMERS" MODIFY ("CSTMR_LAST_NM" NOT NULL ENABLE);

----------------------------------
-- Constraints for Table CUSTOMER_ADDRESS
----------------------------------
ALTER TABLE "CMS"."CUSTOMER_ADDRESS" ADD CONSTRAINT "CUSTOMER_ADDRESS_PK" PRIMARY KEY ("ADDR_ID")
USING INDEX
TABLESPACE "LAUREN" ENABLE;

ALTER TABLE "CMS"."CUSTOMER_ADDRESS" MODIFY ("ADDR_ID" NOT NULL ENABLE);

ALTER TABLE "CMS"."CUSTOMER_ADDRESS" MODIFY ("STREET_LINE_1" NOT NULL ENABLE);

ALTER TABLE "CMS"."CUSTOMER_ADDRESS" MODIFY ("CITY_NM" NOT NULL ENABLE);

ALTER TABLE "CMS"."CUSTOMER_ADDRESS" MODIFY ("ZIP_CD" NOT NULL ENABLE);

ALTER TABLE "CMS"."CUSTOMER_ADDRESS" MODIFY ("DEFAULT_IND" NOT NULL ENABLE);

ALTER TABLE "CMS"."CUSTOMER_ADDRESS" MODIFY ("CSTMR_ID" NOT NULL ENABLE);

ALTER TABLE "CMS"."CUSTOMER_ADDRESS" MODIFY ("CNTRY_CD" NOT NULL ENABLE);

ALTER TABLE "CMS"."CUSTOMER_ADDRESS" MODIFY ("STATE_CD" NOT NULL ENABLE);

----------------------------------
-- Constraints for Table CUSTOMER_CONTACT
----------------------------------
ALTER TABLE "CMS"."CUSTOMER_CONTACT" ADD CONSTRAINT "CUSTOMER_CONTACT_PK" PRIMARY KEY ("CNTCT_ID")
USING INDEX
TABLESPACE "LAUREN" ENABLE;

ALTER TABLE "CMS"."CUSTOMER_CONTACT" MODIFY ("CNTCT_ID" NOT NULL ENABLE);

ALTER TABLE "CMS"."CUSTOMER_CONTACT" MODIFY ("DEFAULT_IND" NOT NULL ENABLE);

ALTER TABLE "CMS"."CUSTOMER_CONTACT" MODIFY ("CSTMR_ID" NOT NULL ENABLE);

----------------------------------
-- Constraints for Table ORDERS
----------------------------------
ALTER TABLE "CMS"."ORDERS" ADD CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ORDR_ID")
USING INDEX
TABLESPACE "LAUREN" ENABLE;

ALTER TABLE "CMS"."ORDERS" MODIFY ("ORDR_ID" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDERS" MODIFY ("ORDR_DT" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDERS" MODIFY ("CSTMR_ID" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDERS" MODIFY ("ADDR_ID" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDERS" MODIFY ("CANCEL_IND" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDERS" MODIFY ("COMPLETE_IND" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDERS" MODIFY ("RETURN_IND" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDERS" MODIFY ("ORDR_STAT_CD" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDERS" MODIFY ("CNTCT_ID" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDERS" MODIFY ("ORDR_TOTAL_COST" NOT NULL ENABLE);

----------------------------------
-- Constraints for Table ORDER_STATUS
----------------------------------
ALTER TABLE "CMS"."ORDER_STATUS" ADD CONSTRAINT "ORDER_STATUS_PK" PRIMARY KEY ("ORDR_STAT_CD")
USING INDEX
TABLESPACE "LAUREN" ENABLE;

ALTER TABLE "CMS"."ORDER_STATUS" MODIFY ("ORDR_STAT_CD" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDER_STATUS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);

----------------------------------
-- Constraints for Table ORDER_TRACKING
----------------------------------
ALTER TABLE "CMS"."ORDER_TRACKING" ADD CONSTRAINT "ORDER_TRACKING_PK" PRIMARY KEY ("ORDR_HIST_ID")
USING INDEX
TABLESPACE "LAUREN" ENABLE;

ALTER TABLE "CMS"."ORDER_TRACKING" MODIFY ("ORDR_HIST_ID" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDER_TRACKING" MODIFY ("STAT_DT" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDER_TRACKING" MODIFY ("ORDR_ID" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDER_TRACKING" MODIFY ("ORDR_STAT_CD" NOT NULL ENABLE);

----------------------------------
-- Constraints for Table ORDER_CONTENTS
----------------------------------
ALTER TABLE "CMS"."ORDER_CONTENTS" ADD CONSTRAINT "ORDER_CONTENTS_PK" PRIMARY KEY ("ORDR_CONTENTS_ID")
USING INDEX
TABLESPACE "LAUREN" ENABLE;

ALTER TABLE "CMS"."ORDER_CONTENTS" MODIFY ("ORDR_CONTENTS_ID" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDER_CONTENTS" MODIFY ("ORDR_ID" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDER_CONTENTS" MODIFY ("PRDCT_ID" NOT NULL ENABLE);

ALTER TABLE "CMS"."ORDER_CONTENTS" MODIFY ("PRDCT_CNT" NOT NULL ENABLE);

----------------------------------
-- Constraints for Table PRODUCTS
----------------------------------
ALTER TABLE "CMS"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("PRDCT_ID")
USING INDEX
TABLESPACE "LAUREN" ENABLE;

ALTER TABLE "CMS"."PRODUCTS" MODIFY ("PRDCT_ID" NOT NULL ENABLE);

ALTER TABLE "CMS"."PRODUCTS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);

ALTER TABLE "CMS"."PRODUCTS" MODIFY ("IN_STOCK_IND" NOT NULL ENABLE);

ALTER TABLE "CMS"."PRODUCTS" MODIFY ("PRICE_PER_UNIT" NOT NULL ENABLE);

----------------------------------
-- Constraints for Table STATE
----------------------------------
ALTER TABLE "CMS"."STATE" ADD CONSTRAINT "STATE_PK" PRIMARY KEY ("STATE_CD")
USING INDEX
TABLESPACE "LAUREN" ENABLE;

ALTER TABLE "CMS"."STATE" MODIFY ("STATE_CD" NOT NULL ENABLE);

ALTER TABLE "CMS"."STATE" MODIFY ("CNTRY_CD" NOT NULL ENABLE);

ALTER TABLE "CMS"."STATE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);

----------------------------------
-- Constraints for Table COUNTRY
----------------------------------
ALTER TABLE "CMS"."COUNTRY" ADD CONSTRAINT "COUNTRY_PK" PRIMARY KEY ("CNTRY_CD")
USING INDEX
TABLESPACE "LAUREN" ENABLE;

ALTER TABLE "CMS"."COUNTRY" MODIFY ("CNTRY_CD" NOT NULL ENABLE);

ALTER TABLE "CMS"."COUNTRY" MODIFY ("DESCRIPTION" NOT NULL ENABLE);

---------------------------------------------
-- Ref Constraints for Table CUSTOMER_ADDRESS
---------------------------------------------

ALTER TABLE "CMS"."CUSTOMER_ADDRESS" ADD CONSTRAINT "CSTMR_ADDR_FK" FOREIGN KEY ("CSTMR_ID")
	REFERENCES "CMS"."CUSTOMERS" ("CSTMR_ID") ON DELETE CASCADE ENABLE;
	
ALTER TABLE "CMS"."CUSTOMER_ADDRESS" ADD CONSTRAINT "ADDR_STATE_FK" FOREIGN KEY ("STATE_CD")
	REFERENCES "CMS"."STATE" ("STATE_CD") ENABLE;

ALTER TABLE "CMS"."CUSTOMER_ADDRESS" ADD CONSTRAINT "ADDR_COUNTRY_FK" FOREIGN KEY ("CNTRY_CD")
	REFERENCES "CMS"."COUNTRY" ("CNTRY_CD") ENABLE;	

---------------------------------------------
-- Ref Constraints for Table CUSTOMER_CONTACT
---------------------------------------------

ALTER TABLE "CMS"."CUSTOMER_CONTACT" ADD CONSTRAINT "CSTMR_CNTCT_FK" FOREIGN KEY ("CSTMR_ID")
	REFERENCES "CMS"."CUSTOMERS" ("CSTMR_ID") ON DELETE CASCADE ENABLE;

---------------------------------------------
-- Ref Constraints for Table ORDERS
---------------------------------------------

ALTER TABLE "CMS"."ORDERS" ADD CONSTRAINT "CSTMR_ORDR_FK" FOREIGN KEY ("CSTMR_ID")
	REFERENCES "CMS"."CUSTOMERS" ("CSTMR_ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "CMS"."ORDERS" ADD CONSTRAINT "ORDR_ADDR_FK" FOREIGN KEY ("ADDR_ID")
	REFERENCES "CMS"."CUSTOMER_ADDRESS" ("ADDR_ID") ENABLE;

ALTER TABLE "CMS"."ORDERS" ADD CONSTRAINT "ORDR_STAT_FK" FOREIGN KEY ("ORDR_STAT_CD")
	REFERENCES "CMS"."ORDER_STATUS" ("ORDR_STAT_CD") ENABLE;
	
ALTER TABLE "CMS"."ORDERS" ADD CONSTRAINT "ORDR_CNTCT_FK" FOREIGN KEY ("CNTCT_ID")
	REFERENCES "CMS"."CUSTOMER_CONTACT" ("CNTCT_ID") ENABLE;	

---------------------------------------------
-- Ref Constraints for Table ORDER_TRACKING
---------------------------------------------

ALTER TABLE "CMS"."ORDER_TRACKING" ADD CONSTRAINT "ORDR_HIST_FK" FOREIGN KEY ("ORDR_ID")
	REFERENCES "CMS"."ORDERS" ("ORDR_ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "CMS"."ORDER_TRACKING" ADD CONSTRAINT "ORDR_HIST_STAT_FK" FOREIGN KEY ("ORDR_STAT_CD")
	REFERENCES "CMS"."ORDER_STATUS" ("ORDR_STAT_CD") ENABLE;

---------------------------------------------
-- Ref Constraints for Table ORDER_CONTENTS
---------------------------------------------

ALTER TABLE "CMS"."ORDER_CONTENTS" ADD CONSTRAINT "ORDR_CONTENTS_FK" FOREIGN KEY ("ORDR_ID")
	REFERENCES "CMS"."ORDERS" ("ORDR_ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "CMS"."ORDER_CONTENTS" ADD CONSTRAINT "ORDR_PRDCT_FK" FOREIGN KEY ("PRDCT_ID")
	REFERENCES "CMS"."PRODUCTS" ("PRDCT_ID") ENABLE;

---------------------------------------------
-- Ref Constraints for Table STATE
---------------------------------------------

ALTER TABLE "CMS"."STATE" ADD CONSTRAINT "STATE_CNTRY_FK" FOREIGN KEY ("CNTRY_CD")
	REFERENCES "CMS"."COUNTRY" ("CNTRY_CD") ON DELETE CASCADE ENABLE;
	
--------------------------------------------
-- DDL for Sequence CUSTOMER_ID_SEQ
--------------------------------------------

CREATE SEQUENCE "CMS"."CUSTOMER_ID_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 10000 NOCACHE NOORDER NOCYCLE
/

--------------------------------------------
-- DDL for Sequence CUSTOMER_ADDRESS_ID_SEQ
--------------------------------------------

CREATE SEQUENCE "CMS"."CUSTOMER_ADDRESS_ID_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 10000 NOCACHE NOORDER NOCYCLE
/

--------------------------------------------
-- DDL for Sequence CUSTOMER_CONTACT_SEQ
--------------------------------------------

CREATE SEQUENCE "CMS"."CUSTOMER_CONTACT_ID_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 10000 NOCACHE NOORDER NOCYCLE
/

--------------------------------------------
-- DDL for Sequence ORDER_ID_SEQ
--------------------------------------------

CREATE SEQUENCE "CMS"."ORDER_ID_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 10000 NOCACHE NOORDER NOCYCLE
/

--------------------------------------------
-- DDL for Sequence ORDER_CONTENTS_ID_SEQ
--------------------------------------------

CREATE SEQUENCE "CMS"."ORDER_CONTENTS_ID_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 10000 NOCACHE NOORDER NOCYCLE
/

--------------------------------------------
-- DDL for Sequence ORDER_TRACKING_ID_SEQ
--------------------------------------------

CREATE SEQUENCE "CMS"."ORDER_TRACKING_ID_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 10000 NOCACHE NOORDER NOCYCLE
/

--------------------------------------------
-- DDL for Sequence PRODUCT_ID_SEQ
--------------------------------------------

CREATE SEQUENCE "CMS"."PRODUCT_ID_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 10000 NOCACHE NOORDER NOCYCLE
/
